#!/usr/bin/env python3
import http.server
import sys

port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000

http.server.test(
    HandlerClass=http.server.SimpleHTTPRequestHandler,
    port=port,
)
